name: checks
on: push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: cache `.yarn/cache`
        uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-v2-${{ hashfiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v2

      - name: save `node_modules`
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashfiles('**/yarn.lock') }}
      - run: yarn install

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - name: restore `node_modules`
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashfiles('**/yarn.lock') }}
      - run: yarn tsc --noEmit

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - name: restore `node_modules`
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashfiles('**/yarn.lock') }}
      - run: yarn eslint .
