name: deploy
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install Nix
        uses: cachix/install-nix-action@v15

      - uses: cachix/cachix-action@v8
        with:
          name: kf-website
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - name: build
        id: build
        run: |
          nix build
          echo "::set-output name=dist::$(readlink result)"

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: kf-website-${{ github.sha }}
          path: ${{ steps.build.outputs.dist }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: install Nix
        uses: cachix/install-nix-action@v15

      - name: configure ipfs-cli
        run: |
          nix run ipfs pin remote service add pinata \
            https://api.pinata.cloud/psa \
            ${{ secrets.PINATA_JWT }}

      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: kf-website

      - name: publish website on ipfs
        run: |
          ipfs add -rQ kf-website | tee ipfs_cid

      - name: save cid as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: ipfs_cid-${{ github.sha }}
          path: ipfs_cid
