name: deploy
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install Nix
        uses: cachix/install-nix-action@v16

      - uses: cachix/cachix-action@v8
        with:
          name: kf-website
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: build
        id: build
        run: |
          nix build
          echo "::set-output name=dist::$(readlink result)"

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: kf-website-${{ github.sha }}
          path: ${{ steps.build.outputs.dist }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: kf-website-${{ github.sha }}
          path: kf-website

      - uses: ipfs/download-ipfs-distribution-action@v1

      - uses: ipfs/start-ipfs-daemon-action@v1

      - name: publish the website on ipfs
        id: publish
        run: |
          ipfs add -rQ kf-website | tee ipfs_cid
          echo "::set-output name=cid::$(cat ipfs_cid)"

      - name: pin the website using pinata
        run: |
          ipfs pin remote service add pinata \
            https://api.pinata.cloud/psa \
            ${{ secrets.PINATA_JWT }}
          ipfs pin remote add --service=pinata "${{ steps.publish.outputs.cid }}"

      - uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          status: success
          name: IPFS Deploy
          url: "https://ipfs.io/ipfs/${{ steps.publish.outputs.cid }}"
          description: "CID: ${{ steps.publish.outputs.cid }}"
